# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Move Forward CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for MongoDB to be ready
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 27017 && echo Success && exit 0
            echo "Waiting for MongoDB..."
            sleep 1
          done
          echo "MongoDB did not start in time" && exit 1

      - name: Check Linting
        run: npm run build --if-present

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test
